// Templates de champs pour chaque secteur
export const reportTemplates = {
  Direction: [
    { id: "meetingType", label: "Type de réunion", type: "select" as const, options: ["Comité de direction", "Conseil d'administration", "Réunion stratégique"] },
    { id: "meetingDate", label: "Date de la réunion", type: "date" as const },
    { id: "participants", label: "Participants présents (nombre)", type: "number" as const },
    { id: "decisions", label: "Décisions prises", type: "textarea" as const },
    { id: "actions", label: "Actions à mener", type: "textarea" as const },
    { id: "deadline", label: "Échéance prioritaire", type: "date" as const },
    { id: "budget", label: "Budget alloué (Ariary)", type: "number" as const },
    { id: "status", label: "Statut", type: "select" as const, options: ["En cours", "Validé", "En attente"] },
  ],
  Studies: [
    { id: "studyType", label: "Type d'étude", type: "select" as const, options: ["Marketing", "Macroéconomie", "Sectorielle", "Autre"] },
    { id: "clientName", label: "Nom du client", type: "text" as const },
    { id: "startDate", label: "Date de début du projet", type: "date" as const },
    { id: "endDate", label: "Date de fin prévue", type: "date" as const },
    { id: "methodology", label: "Méthodologie utilisée", type: "select" as const, options: ["Quantitative", "Qualitative", "Mixte"] },
    { id: "sampleSize", label: "Taille de l'échantillon", type: "number" as const },
    { id: "zones", label: "Zones d'intervention", type: "text" as const },
    { id: "progress", label: "Avancement du projet (%)", type: "number" as const },
    { id: "deliverables", label: "Livrables attendus", type: "textarea" as const },
    { id: "observations", label: "Observations/Défis rencontrés", type: "textarea" as const },
  ],
  IT: [
    { id: "interventionType", label: "Type d'intervention", type: "select" as const, options: ["Maintenance", "Installation", "Dépannage", "Développement", "Réseau"] },
    { id: "hardware", label: "Matériel concerné", type: "text" as const },
    { id: "software", label: "Logiciel concerné", type: "text" as const },
    { id: "ticketNumber", label: "Numéro de ticket", type: "text" as const },
    { id: "priority", label: "Priorité", type: "select" as const, options: ["Urgent", "Élevée", "Moyenne", "Faible"] },
    { id: "interventionDate", label: "Date de l'intervention", type: "date" as const },
    { id: "duration", label: "Durée d'intervention (heures)", type: "number" as const },
    { id: "problem", label: "Problème identifié", type: "textarea" as const },
    { id: "solution", label: "Solution apportée", type: "textarea" as const },
    { id: "status", label: "Statut", type: "select" as const, options: ["Résolu", "En cours", "En attente de pièces", "Escaladé"] },
  ],
  Finance: [
    { id: "operationType", label: "Type d'opération", type: "select" as const, options: ["Facture client", "Facture fournisseur", "Paie", "Banque", "Caisse"] },
    { id: "documentNumber", label: "Numéro de pièce comptable", type: "text" as const },
    { id: "operationDate", label: "Date de l'opération", type: "date" as const },
    { id: "amount", label: "Montant (Ariary)", type: "number" as const },
    { id: "beneficiary", label: "Bénéficiaire/Client", type: "text" as const },
    { id: "paymentMethod", label: "Mode de paiement", type: "select" as const, options: ["Espèces", "Chèque", "Virement", "Mobile Money"] },
    { id: "bankAccount", label: "Compte bancaire", type: "text" as const },
    { id: "project", label: "Projet/Mission associé(e)", type: "text" as const },
    { id: "attachments", label: "Justificatifs attachés", type: "select" as const, options: ["Oui", "Non"] },
    { id: "observations", label: "Observations", type: "textarea" as const },
  ],
  Quality: [
    { id: "activityType", label: "Type d'activité", type: "select" as const, options: ["Audit qualité", "Contrôle données", "Analyse statistique", "Formation méthodologie"] },
    { id: "project", label: "Projet/Étude concerné(e)", type: "text" as const },
    { id: "controlDate", label: "Date de contrôle", type: "date" as const },
    { id: "questionnairesChecked", label: "Nombre de questionnaires vérifiés", type: "number" as const },
    { id: "errorRate", label: "Taux d'erreur (%)", type: "number" as const },
    { id: "nonConformities", label: "Non-conformités détectées", type: "number" as const },
    { id: "correctiveActions", label: "Actions correctives proposées", type: "textarea" as const },
    { id: "validationStatus", label: "Statut de validation", type: "select" as const, options: ["Conforme", "Non-conforme", "En correction"] },
    { id: "correctionDeadline", label: "Délai de correction", type: "date" as const },
    { id: "responsible", label: "Responsable de suivi", type: "text" as const },
  ],
  Field: [
    { id: "surveyType", label: "Type d'enquête", type: "select" as const, options: ["Face-à-face", "Téléphonique", "En ligne", "Observation"] },
    { id: "studyName", label: "Nom de l'étude/Projet", type: "text" as const },
    { id: "collectionDate", label: "Date de collecte", type: "date" as const },
    { id: "completedQuestionnaires", label: "Nombre de questionnaires complétés", type: "number" as const },
    { id: "refusals", label: "Nombre de refus", type: "number" as const },
    { id: "responseRate", label: "Taux de réponse (%)", type: "number" as const },
    { id: "locations", label: "Villages/Quartiers visités", type: "text" as const },
    { id: "supervisor", label: "Superviseur terrain", type: "text" as const },
    { id: "difficulties", label: "Difficultés rencontrées", type: "textarea" as const },
    { id: "equipment", label: "Matériel utilisé", type: "select" as const, options: ["Tablette", "Papier", "Smartphone"] },
    { id: "missionCost", label: "Frais de mission (Ariary)", type: "number" as const },
  ],
  Admin: [
    { id: "activityType", label: "Type d'activité", type: "select" as const, options: ["Courrier", "Logistique", "Secrétariat", "Gardiennage", "Entretien"] },
    { id: "activityDate", label: "Date de l'activité", type: "date" as const },
    { id: "requester", label: "Demandeur/Service", type: "text" as const },
    { id: "taskDescription", label: "Description de la tâche", type: "textarea" as const },
    { id: "materials", label: "Matériel/Fournitures utilisé(e)s", type: "text" as const },
    { id: "vehicle", label: "Véhicule utilisé (le cas échéant)", type: "text" as const },
    { id: "mileage", label: "Kilométrage parcouru", type: "number" as const },
    { id: "cost", label: "Coût engagé (Ariary)", type: "number" as const },
    { id: "documentsProcessed", label: "Documents traités", type: "number" as const },
    { id: "status", label: "Statut", type: "select" as const, options: ["Effectué", "En cours", "Reporté"] },
  ],
};
